### ISSUE TITLE
Error while building an app

### ISSUE THREAD

**Issue by kasteckis** [Martynas-S/KTU-AIS-Chrome-extension#1]
Hey, ar projektas vis dar supportinamas?

Kiek aš supratau, tai parsisiuntus repositoriją, susibuildinus ir susiinstaliavus reikia tiesiog įkelti į extensionus, tai yra nebūtina būti visada paleidus node aplinkos?

Vykdant npm install komandą gaunamas tosk error
![image](https://user-images.githubusercontent.com/41127259/84363722-cf275080-abd7-11ea-9355-46c97809bfa1.png)

Jeigu iš tavo pusės viskas vis dar veikia, galbūt galėtum tiesiog sukurti release, kur galima būtu tiesiog parsisiųsti extensioną? https://github.com/Martynas-S/KTU-AIS-Chrome-extension/releases

Thanks in advance

**Comment by Martynas-S** [comment]
Sveikas,

Šiaip nežinau ar dar viskas veikia, nes lyg dažnokai keičiasi tos KTU autentifikacijos varkės.
Projektas apleistas nes mane už ip bannino KTU AIS dėl to, kad per dažnai pingindavau ir scrapindavau pažymius :D 

Jeigu paskaitysi error message kurį atsiuntei tai pastebėsi, kad reikia node >= 10.0, o past tave node 8.10.0 ;).

Jeigu netingi gali pasižiūrėt ar veikia ir jei ne, tai sutvarkyt projektą ir padaryt pull requestą :D

**Comment by kasteckis** [comment]
Oh, aš maniau, ten tiesiog warning, o ne error. Realiai pasiupdatinau node ir npm iki newest ir gaunu tokius error.

![image](https://user-images.githubusercontent.com/41127259/84401049-7a053200-ac0b-11ea-9ec8-97530f2ec016.png)


Šiaip jeigu gal turi tiesiog sucompilintą extensioną t.y. tą papkę kurią reikėtu įsikelti į chrome, gal galėtum tiesiog release pakurti? Kad tiesiog užtektu parsisiųsti ir įsikelti to thest if it works.
